/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * ReeLuv API
 * ShowReelとVideoClipを管理するAPI
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  CreateVideoClipResponse,
  VideoClipDetailResponse,
  VideoClipListResponse
} from '.././model';


export const getGetApiClipsResponseMock = (overrideResponse: Partial< VideoClipListResponse > = {}): VideoClipListResponse => ({data: {clips: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), videoStandard: faker.string.alpha({length: {min: 10, max: 20}}), videoDefinition: faker.string.alpha({length: {min: 10, max: 20}}), startTimecode: faker.string.alpha({length: {min: 10, max: 20}}), endTimecode: faker.string.alpha({length: {min: 10, max: 20}}), duration: faker.string.alpha({length: {min: 10, max: 20}})}))}, ...overrideResponse})

export const getPostApiClipsResponseMock = (overrideResponse: Partial< CreateVideoClipResponse > = {}): CreateVideoClipResponse => ({data: {id: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), videoStandard: faker.string.alpha({length: {min: 10, max: 20}}), videoDefinition: faker.string.alpha({length: {min: 10, max: 20}}), startTimecode: faker.string.alpha({length: {min: 10, max: 20}}), endTimecode: faker.string.alpha({length: {min: 10, max: 20}}), duration: faker.string.alpha({length: {min: 10, max: 20}})}, ...overrideResponse})

export const getGetApiClipsIdResponseMock = (overrideResponse: Partial< VideoClipDetailResponse > = {}): VideoClipDetailResponse => ({data: {id: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), videoStandard: faker.string.alpha({length: {min: 10, max: 20}}), videoDefinition: faker.string.alpha({length: {min: 10, max: 20}}), startTimecode: faker.string.alpha({length: {min: 10, max: 20}}), endTimecode: faker.string.alpha({length: {min: 10, max: 20}}), duration: faker.string.alpha({length: {min: 10, max: 20}})}, ...overrideResponse})


export const getGetApiClipsMockHandler = (overrideResponse?: VideoClipListResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<VideoClipListResponse> | VideoClipListResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/clips', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiClipsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getPostApiClipsMockHandler = (overrideResponse?: CreateVideoClipResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CreateVideoClipResponse> | CreateVideoClipResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/clips', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiClipsResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetApiClipsIdMockHandler = (overrideResponse?: VideoClipDetailResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<VideoClipDetailResponse> | VideoClipDetailResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/clips/:id', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiClipsIdResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getClipMock = () => [
  getGetApiClipsMockHandler(),
  getPostApiClipsMockHandler(),
  getGetApiClipsIdMockHandler()
]
