/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * ReeLuv API
 * ShowReelとVideoClipを管理するAPI
 * OpenAPI spec version: 1.0.0
 */
import type { CreateVideoClipRequestVideoStandard } from './createVideoClipRequestVideoStandard';
import type { CreateVideoClipRequestVideoDefinition } from './createVideoClipRequestVideoDefinition';

export interface CreateVideoClipRequest {
  /** @minLength 1 */
  name: string;
  /** @nullable */
  description?: string | null;
  videoStandard: CreateVideoClipRequestVideoStandard;
  videoDefinition: CreateVideoClipRequestVideoDefinition;
  startTimecode: string;
  endTimecode: string;
}
