/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * ReeLuv API
 * ShowReelとVideoClipを管理するAPI
 * OpenAPI spec version: 1.0.0
 */

export type CreateVideoClipRequestVideoDefinition =
  (typeof CreateVideoClipRequestVideoDefinition)[keyof typeof CreateVideoClipRequestVideoDefinition]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateVideoClipRequestVideoDefinition = {
  SD: 'SD',
  HD: 'HD',
} as const
