/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * ReeLuv API
 * ShowReelとVideoClipを管理するAPI
 * OpenAPI spec version: 1.0.0
 */

export type CreateShowReelRequestVideoStandard = typeof CreateShowReelRequestVideoStandard[keyof typeof CreateShowReelRequestVideoStandard];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateShowReelRequestVideoStandard = {
  PAL: 'PAL',
  NTSC: 'NTSC',
} as const;
