/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * ReeLuv API
 * ShowReelとVideoClipを管理するAPI
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiReelsIdClipsClipId400Error } from './deleteApiReelsIdClipsClipId400Error'

/**
 * リクエストが不正です
 */
export type DeleteApiReelsIdClipsClipId400 = {
  error: DeleteApiReelsIdClipsClipId400Error
}
