/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * ReeLuv API
 * ShowReelとVideoClipを管理するAPI
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiReelsIdClips400Error } from './deleteApiReelsIdClips400Error';

/**
 * リクエストが不正です
 */
export type DeleteApiReelsIdClips400 = {
  error: DeleteApiReelsIdClips400Error;
};
