/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * ReeLuv API
 * ShowReelとVideoClipを管理するAPI
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiReelsId404Error } from './getApiReelsId404Error'

/**
 * リソースが見つかりません
 */
export type GetApiReelsId404 = {
  error: GetApiReelsId404Error
}
