/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * ReeLuv API
 * ShowReelとVideoClipを管理するAPI
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiReelsIdCompatibleClips404Error } from './getApiReelsIdCompatibleClips404Error'

/**
 * リソースが見つかりません
 */
export type GetApiReelsIdCompatibleClips404 = {
  error: GetApiReelsIdCompatibleClips404Error
}
