/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * ReeLuv API
 * ShowReelとVideoClipを管理するAPI
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiReelsId400Error } from './patchApiReelsId400Error'

/**
 * リクエストが不正です
 */
export type PatchApiReelsId400 = {
  error: PatchApiReelsId400Error
}
