/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * ReeLuv API
 * ShowReelとVideoClipを管理するAPI
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiReels400Error } from './postApiReels400Error';

/**
 * リクエストが不正です
 */
export type PostApiReels400 = {
  error: PostApiReels400Error;
};
