/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * ReeLuv API
 * ShowReelとVideoClipを管理するAPI
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiClips400Error } from './postApiClips400Error';

/**
 * リクエストが不正です
 */
export type PostApiClips400 = {
  error: PostApiClips400Error;
};
