/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * ReeLuv API
 * ShowReelとVideoClipを管理するAPI
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiReelsIdClips400Error } from './postApiReelsIdClips400Error'

/**
 * リクエストが不正です
 */
export type PostApiReelsIdClips400 = {
  error: PostApiReelsIdClips400Error
}
