/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * ReeLuv API
 * ShowReelとVideoClipを管理するAPI
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiReelsIdClips404Error } from './postApiReelsIdClips404Error';

/**
 * リソースが見つかりません
 */
export type PostApiReelsIdClips404 = {
  error: PostApiReelsIdClips404Error;
};
