/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * ReeLuv API
 * ShowReelとVideoClipを管理するAPI
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiReelsIdClipsReorder404Error } from './putApiReelsIdClipsReorder404Error'

/**
 * リソースが見つかりません
 */
export type PutApiReelsIdClipsReorder404 = {
  error: PutApiReelsIdClipsReorder404Error
}
