/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * ReeLuv API
 * ShowReelとVideoClipを管理するAPI
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiReelsIdClipsReorder400Error } from './putApiReelsIdClipsReorder400Error'

/**
 * リクエストが不正です
 */
export type PutApiReelsIdClipsReorder400 = {
  error: PutApiReelsIdClipsReorder400Error
}
