/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * ReeLuv API
 * ShowReelとVideoClipを管理するAPI
 * OpenAPI spec version: 1.0.0
 */

export type RemoveClipOperationResponseData = {
  showReelId: string;
  /** 削除されたクリップのインデックス */
  clipIndex: number;
  clipCount: number;
  totalDuration: string;
  updatedAt: string;
};
