/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * ReeLuv API
 * ShowReelとVideoClipを管理するAPI
 * OpenAPI spec version: 1.0.0
 */
import type { RemoveClipOperationResponseData } from './removeClipOperationResponseData';

export interface RemoveClipOperationResponse {
  data: RemoveClipOperationResponseData;
}
