/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * ReeLuv API
 * ShowReelとVideoClipを管理するAPI
 * OpenAPI spec version: 1.0.0
 */

export interface RemoveClipRequest {
  /**
   * 削除するクリップのインデックス（0始まり）
   * @minimum 0
   */
  index: number;
}
