/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * ReeLuv API
 * ShowReelとVideoClipを管理するAPI
 * OpenAPI spec version: 1.0.0
 */
import type { ShowReelClip } from './showReelClip';

export interface ShowReelDetail {
  id: string;
  name: string;
  videoStandard: string;
  videoDefinition: string;
  clips: ShowReelClip[];
  clipCount: number;
  totalDuration: string;
  createdAt: string;
  updatedAt: string;
}
